version: "3"

services:
  strapi:
    build: .
    container_name: strapi-app
    restart: unless-stopped
    ports:
      - "1337:1337"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
